// @ts-check
/**
 * Expo config plugin entry point for react-native-unimp.
 *
 * Expo's CLI loads this file during `expo prebuild` to automatically
 * configure the native projects for the UniMP SDK.
 *
 * The TypeScript source lives in `plugin/src/`.  This file re-exports
 * the compiled output from `plugin/build/` (generated by the
 * `build:plugin` npm script).  When running from source (e.g. in a
 * monorepo with transpilation), the TypeScript source is loaded
 * directly via the fallback `require` call.
 */

let plugin;

try {
  // Try the compiled output first (production / published package)
  plugin = require('./plugin/build/index.js');
} catch {
  // Fallback: load the TypeScript source directly.
  // This works in dev environments with ts-node, jiti, or Expo's
  // built-in TypeScript transpilation (SDK 50+).
  try {
    plugin = require('./plugin/src/index.ts');
  } catch {
    // If neither works, provide a no-op plugin so the app doesn't crash.
    // The user will need to run `npm run build:plugin` first.
    plugin = {
      default: (config) => config,
    };
  }
}

module.exports = plugin.default || plugin;
